# Generated by Django 3.2.18 on 2023-06-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0002_instagram_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagram',
            old_name='content',
            new_name='sosial_media',
        ),
    ]
