# Generated by Django 4.2.6 on 2024-01-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
