# Generated by Django 4.2.6 on 2024-01-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactProfile',
        ),
    ]
