# Generated by Django 4.2.6 on 2024-01-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contactprofile_reportingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingresult',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
