# Generated by Django 3.2.18 on 2023-05-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='kecamatan',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='kelurahan',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
